// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/product_sections/data/repositories/products_sections_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower/config/base/base_response.dart' as _i4;
import 'package:flower/features/product_sections/data/datasource/products_section_data_source_contract.dart'
    as _i2;
import 'package:flower/features/product_sections/data/models/dtos/occasion_dto.dart'
    as _i5;
import 'package:flower/features/product_sections/data/models/dtos/product_dto.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductsSectionDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsSectionDataSourceContract extends _i1.Mock
    implements _i2.ProductsSectionDataSourceContract {
  MockProductsSectionDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.OccasionDto>>> getOccasions({
    int? limit,
    int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, [], {#limit: limit, #page: page}),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.OccasionDto>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.OccasionDto>>>(
                    this,
                    Invocation.method(#getOccasions, [], {
                      #limit: limit,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.OccasionDto>>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i7.ProductDto>>> getProducts({
    int? limit,
    String? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#limit: limit, #sort: sort}),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i7.ProductDto>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i7.ProductDto>>>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #limit: limit,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i7.ProductDto>>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.ProductDto>> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i3.Future<_i4.BaseResponse<_i7.ProductDto>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i7.ProductDto>>(
                this,
                Invocation.method(#getProductById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.ProductDto>>);
}
