// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/edit_profile/api/datasource/edit_profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:flower/core/network/model/profile_response/profile_response.dart'
    as _i2;
import 'package:flower/features/edit_profile/api/api_client/edit_profile_api_client.dart'
    as _i3;
import 'package:flower/features/edit_profile/data/models/edit_profile_request.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileResponseDto_0 extends _i1.SmartFake
    implements _i2.ProfileResponseDto {
  _FakeProfileResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileApiClient extends _i1.Mock
    implements _i3.EditProfileApiClient {
  MockEditProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileResponseDto> editProfile(
    _i5.EditProfileRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i4.Future<_i2.ProfileResponseDto>.value(
              _FakeProfileResponseDto_0(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ProfileResponseDto>);

  @override
  _i4.Future<_i2.ProfileResponseDto> uploadPhoto(_i6.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [photo]),
            returnValue: _i4.Future<_i2.ProfileResponseDto>.value(
              _FakeProfileResponseDto_0(
                this,
                Invocation.method(#uploadPhoto, [photo]),
              ),
            ),
          )
          as _i4.Future<_i2.ProfileResponseDto>);
}
