// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/edit_profile/presentation/cubit/edit_profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower/config/base/base_response.dart' as _i4;
import 'package:flower/core/network/model/user_models/user_entity.dart' as _i5;
import 'package:flower/features/edit_profile/domain/usecases/edit_profile_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i2.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.UserEntity>> call({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
            }),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.UserEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.UserEntity>>(
                this,
                Invocation.method(#call, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.UserEntity>>);
}
