// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/auth/api/datasources/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flower/features/auth/api/api_client/auth_api_client.dart'
    as _i6;
import 'package:flower/features/auth/data/models/request/forget_password_request.dart'
    as _i9;
import 'package:flower/features/auth/data/models/request/register_request.dart'
    as _i8;
import 'package:flower/features/auth/data/models/request/reset_password_request.dart'
    as _i11;
import 'package:flower/features/auth/data/models/request/verify_reset_code_request.dart'
    as _i10;
import 'package:flower/features/auth/data/models/response/forget_password_response.dart'
    as _i3;
import 'package:flower/features/auth/data/models/response/register_response.dart'
    as _i2;
import 'package:flower/features/auth/data/models/response/reset_password_response.dart'
    as _i5;
import 'package:flower/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_2 extends _i1.SmartFake
    implements _i4.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i6.AuthApiClient {
  MockAuthApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.RegisterResponseDto> register(
    _i8.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i7.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.RegisterResponseDto>);

  @override
  _i7.Future<_i3.ForgetPasswordResponseDto> forgotPassword(
    _i9.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i7.Future<_i3.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_1(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i7.Future<_i3.ForgetPasswordResponseDto>);

  @override
  _i7.Future<_i4.VerifyResetCodeResponseDto> verifyResetCode(
    _i10.VerifyResetCodeRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i7.Future<_i4.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_2(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i7.Future<_i4.VerifyResetCodeResponseDto>);

  @override
  _i7.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i11.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i7.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.ResetPasswordResponseDto>);
}
