// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/product_sections/api/datasource/categories_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flower/config/base/base_response.dart' as _i8;
import 'package:flower/core/network/safe_api_caller.dart' as _i7;
import 'package:flower/features/product_sections/api/api_client/products_sections_api_client.dart'
    as _i5;
import 'package:flower/features/product_sections/data/models/response/categories_response.dart'
    as _i2;
import 'package:flower/features/product_sections/data/models/response/occasions_response.dart'
    as _i3;
import 'package:flower/features/product_sections/data/models/response/products_response.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.CategoriesResponse {
  _FakeCategoriesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOccasionsResponse_1 extends _i1.SmartFake
    implements _i3.OccasionsResponse {
  _FakeOccasionsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponse_2 extends _i1.SmartFake
    implements _i4.ProductsResponse {
  _FakeProductsResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsSectionsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsSectionsApiClient extends _i1.Mock
    implements _i5.ProductsSectionsApiClient {
  MockProductsSectionsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CategoriesResponse> getCategories({int? limit, int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [], {#limit: limit, #page: page}),
            returnValue: _i6.Future<_i2.CategoriesResponse>.value(
              _FakeCategoriesResponse_0(
                this,
                Invocation.method(#getCategories, [], {
                  #limit: limit,
                  #page: page,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.CategoriesResponse>);

  @override
  _i6.Future<_i3.OccasionsResponse> getOccasions({int? limit, int? page}) =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, [], {#limit: limit, #page: page}),
            returnValue: _i6.Future<_i3.OccasionsResponse>.value(
              _FakeOccasionsResponse_1(
                this,
                Invocation.method(#getOccasions, [], {
                  #limit: limit,
                  #page: page,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.OccasionsResponse>);

  @override
  _i6.Future<_i4.ProductsResponse> getProducts({
    int? limit,
    String? sort,
    String? categoryId,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #limit: limit,
              #sort: sort,
              #categoryId: categoryId,
              #keyword: keyword,
            }),
            returnValue: _i6.Future<_i4.ProductsResponse>.value(
              _FakeProductsResponse_2(
                this,
                Invocation.method(#getProducts, [], {
                  #limit: limit,
                  #sort: sort,
                  #categoryId: categoryId,
                  #keyword: keyword,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.ProductsResponse>);
}

/// A class which mocks [SafeApiCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockSafeApiCaller extends _i1.Mock implements _i7.SafeApiCaller {
  MockSafeApiCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i8.BaseResponse<T>> safeCall<T>(_i6.Future<T> Function()? call) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [call]),
            returnValue: _i6.Future<_i8.BaseResponse<T>>.value(
              _i9.dummyValue<_i8.BaseResponse<T>>(
                this,
                Invocation.method(#safeCall, [call]),
              ),
            ),
          )
          as _i6.Future<_i8.BaseResponse<T>>);
}
