// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/auth/data/repos/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower/config/base/base_response.dart' as _i4;
import 'package:flower/features/auth/data/data_sources/auth_remote_data_source.dart'
    as _i2;
import 'package:flower/features/auth/data/models/response/forget_password_response.dart'
    as _i5;
import 'package:flower/features/auth/data/models/response/reset_password_response.dart'
    as _i8;
import 'package:flower/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRemoteDs].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDs extends _i1.Mock implements _i2.AuthRemoteDs {
  MockAuthRemoteDs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponseDto>> forgetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#email: email}),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i5.ForgetPasswordResponseDto>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i5.ForgetPasswordResponseDto>
                  >(
                    this,
                    Invocation.method(#forgetPassword, [], {#email: email}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponseDto>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.VerifyResetCodeResponseDto>> verifyResetCode({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {#resetCode: resetCode}),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i7.VerifyResetCodeResponseDto>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i7.VerifyResetCodeResponseDto>
                  >(
                    this,
                    Invocation.method(#verifyResetCode, [], {
                      #resetCode: resetCode,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.VerifyResetCodeResponseDto>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.ResetPasswordResponseDto>> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
            }),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i8.ResetPasswordResponseDto>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i8.ResetPasswordResponseDto>
                  >(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #email: email,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ResetPasswordResponseDto>>);
}
