// Mocks generated by Mockito 5.4.6 from annotations
// in flower/test/features/product_sections/presentation/product_details/cubit/product_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower/config/base/base_response.dart' as _i5;
import 'package:flower/features/product_sections/domain/entities/product_entity.dart'
    as _i6;
import 'package:flower/features/product_sections/domain/repositories/products_section_repo.dart'
    as _i2;
import 'package:flower/features/product_sections/domain/use_cases/get_product_by_id_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductsSectionRepo_0 extends _i1.SmartFake
    implements _i2.ProductsSectionRepo {
  _FakeProductsSectionRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProductByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductByIdUseCase extends _i1.Mock
    implements _i3.GetProductByIdUseCase {
  MockGetProductByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductsSectionRepo get productsSectionRepo =>
      (super.noSuchMethod(
            Invocation.getter(#productsSectionRepo),
            returnValue: _FakeProductsSectionRepo_0(
              this,
              Invocation.getter(#productsSectionRepo),
            ),
          )
          as _i2.ProductsSectionRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.ProductEntity>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.ProductEntity>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.ProductEntity>>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ProductEntity>>);
}
